name       : docker-buildx
version    : 0.10.0
release    : 5
source     :
    - git|https://github.com/docker/buildx.git : v0.10.0
license    : Apache-2.0
component  : virt
summary    : Docker CLI plugin for extended build capabilities
description: |
    Docker CLI plugin for extended build capabilities with BuildKit
builddeps  :
    - golang
networking : yes
environment: |
    export _buildx_r=github.com/docker/buildx
    export _cli_plugins_dir=/usr/lib/docker/cli-plugins
    export GO111MODULE=auto

    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GOFLAGS='-buildmode=pie -trimpath -mod=readonly -modcacherw'
build      : |
    mkdir -p src/$_buildx_r
    ln -s `pwd` src/$_buildx_r/buildx
    pushd src/$_buildx_r/buildx

    go build -o docker-buildx \
              -ldflags "-linkmode=external \
              -X $_buildx_r/version.Version=v$version \
              -X $_buildx_r/version.Revision=$(git rev-parse HEAD) \
              -X $_buildx_r/version.Package=$_buildx_r" \
              ./cmd/buildx
install    : |
    install -Ddm00755 $installdir/$_cli_plugins_dir
    install -m00755 docker-buildx $installdir/$_cli_plugins_dir/docker-buildx
